### PR TITLE
Install librsvg

### PR DESCRIPTION
**Pull request by azubieta**

### CODE REVIEW

**Comment by azubieta** [comment]
Travis build is being terminated because it takes too long. @TheAssassin if you have the docker credentials would you mind to build and update it manually please.

**Comment by TheAssassin** [comment]
That's why I said I'd build it manually, yes.

**Review by TheAssassin — CHANGES_REQUESTED** [review]
Please put this into a separate `RUN` command at the bottom, as I told you on IRC, I don't want to rebuild all dependencies.

**Comment by azubieta** [comment]
Done

**Review by TheAssassin — APPROVED** [review]

**Pull request merged**
